import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [
        'overview/architecture-at-a-glance',
        'overview/page-lifecycle',
        'overview/component-taxonomy',
      ],
    },
    {
      type: 'category',
      label: 'Build Pipeline',
      items: [
        'backend/sync-sh',
        'backend/hakyll-hs',
        'backend/bash-sh',
        'backend/preprocess-markdown-hs',
        'backend/generate-directory-hs',
        'backend/generate-link-bibliography-hs',
        'backend/check-metadata-hs',
        'backend/test-hs',
        'php/pre-commit-hook',
        'shell/markdown-lint',
        'backend/markdown-footnote-length-hs',
        'backend/markdown-length-checker-hs',
        'php/anchor-checker',
        'backend/duplicate-quote-site-finder-hs',
        'backend/cycle-hs',
      ],
    },
    {
      type: 'category',
      label: 'Annotation & Metadata',
      items: [
        'backend/link-metadata-hs',
        'backend/annotation-hs',
        'backend/link-metadata-types-hs',
        'backend/gtx-hs',
        'frontend/annotations-js',
        'backend/annotation-arxiv-hs',
        'backend/annotation-biorxiv-hs',
        'backend/annotation-gwernnet-hs',
        'backend/annotation-openreview-hs',
        'backend/annotation-pdf-hs',
        'backend/annotation-dump-hs',
        'shell/openreviewabstract',
        'shell/preprocess-annotation',
        'backend/metadata-author-hs',
        'backend/metadata-date-hs',
        'backend/metadata-format-hs',
        'backend/metadata-title-hs',
        'backend/paragraph-hs',
        'python/date-guesser',
        'python/title-cleaner',
        'python/paragraphizer',
        'python/tagguesser',
        'python/italicizer',
        'python/text2epositive',
        'backend/config-metadata-author-hs',
        'backend/config-metadata-format-hs',
        'backend/config-metadata-title-hs',
      ],
    },
    {
      type: 'category',
      label: 'Popup System',
      items: [
        'frontend/popups-js',
        'frontend/extracts-js',
        'frontend/popins-js',
        'frontend/extracts-annotations-js',
        'frontend/extracts-content-js',
        'frontend/extracts-options-js',
        'frontend/extracts-load-js',
        'backend/link-live-hs',
        'backend/config-link-live-hs',
        'templates/pop-frame-title-standard',
        'templates/annotation-blockquote-inside',
        'templates/annotation-blockquote-outside',
      ],
    },
    {
      type: 'category',
      label: 'Link Processing',
      items: [
        'backend/link-archive-hs',
        'backend/config-link-archive-hs',
        'shell/link-archive',
        'php/deconstruct-singlefile',
        'backend/link-icon-hs',
        'backend/config-link-icon-hs',
        'php/build-icon-sprite-file',
        'backend/link-auto-hs',
        'backend/config-link-auto-hs',
        'backend/interwiki-hs',
        'backend/config-interwiki-hs',
        'backend/link-id-hs',
        'backend/config-link-id-hs',
        'backend/link-suggester-hs',
        'backend/config-link-suggester-hs',
        'backend/link-extractor-hs',
        'backend/link-prioritize-hs',
        'backend/link-titler-hs',
        'backend/link-tooltip-hs',
        'frontend/links-css',
        'css/links',
      ],
    },
    {
      type: 'category',
      label: 'Content Rendering',
      items: [
        'frontend/initial-js',
        'frontend/rewrite-js',
        'frontend/content-js',
        'frontend/transclude-js',
        'frontend/rewrite-initial-js',
        'frontend/utility-js',
        'backend/generate-backlinks-hs',
        'backend/generate-similar-hs',
        'backend/generate-similar-links-hs',
        'backend/config-generate-similar-hs',
        'backend/link-backlink-hs',
      ],
    },
    {
      type: 'category',
      label: 'Typography & Layout',
      items: [
        'backend/typography-hs',
        'backend/config-typography-hs',
        'frontend/typography-js',
        'frontend/sidenotes-js',
        'frontend/collapse-js',
        'frontend/layout-js',
        'backend/columns-hs',
        'backend/inflation-hs',
        'backend/config-inflation-hs',
        'backend/image-hs',
        'frontend/image-focus-js',
        'python/invertornot',
        'python/image-margin-checker',
        'shell/png',
        'php/should-image-have-outline',
        'php/build-inlined-images',
      ],
    },
    {
      type: 'category',
      label: 'Theming & UI',
      items: [
        'frontend/dark-mode-js',
        'frontend/dark-mode-initial-js',
        'css/dark-mode-adjustments',
        'frontend/dark-mode-adjustments-css',
        'php/build-mode-css',
        'frontend/reader-mode-js',
        'frontend/reader-mode-initial-js',
        'frontend/reader-mode-css',
        'css/reader-mode-initial',
        'frontend/color-js',
        'css/colors',
        'frontend/colors-css',
        'php/color-scheme-convert',
        'css/default',
        'frontend/default-css',
        'css/initial',
        'frontend/initial-css',
        'css/light-mode-adjustments',
        'frontend/special-occasions-js',
        'frontend/special-occasions-css',
      ],
    },
    {
      type: 'category',
      label: 'Backend Utilities',
      items: [
        'backend/utils-hs',
        'backend/query-hs',
        'backend/unique-hs',
        'backend/string-replace-hs',
        'backend/rename-hs',
        'backend/config-misc-hs',
        'backend/config-paragraph-hs',
        'backend/nginx-redirect-guesser-hs',
      ],
    },
    {
      type: 'category',
      label: 'Frontend Utilities',
      items: [
        'frontend/misc-js',
        'frontend/console-js',
        'frontend/404-guesser-js',
      ],
    },
    {
      type: 'category',
      label: 'Tags & Navigation',
      items: [
        'backend/tags-hs',
        'backend/config-tags-hs',
        'backend/guess-tag-hs',
        'backend/change-tag-hs',
      ],
    },
    {
      type: 'category',
      label: 'Content Features',
      items: [
        'backend/blog-hs',
        'backend/x-of-the-day-hs',
        'backend/config-x-of-the-day-hs',
      ],
    },
    {
      type: 'category',
      label: 'PHP Asset Pipeline',
      items: [
        'php/build_unified_assets',
        'php/build_asset_versions',
        'php/build-font-css',
        'php/build-versioned-font-css',
        'php/build_head_includes',
        'php/build_body_includes',
        'php/build_standalone_includes',
        'php/build_paths',
        'php/build_variables',
        'php/build_functions',
        'php/version_asset_links',
        'php/asset',
        'php/svg-squeeze',
        'php/svg-strip-background',
        'php/font-spec',
      ],
    },
    {
      type: 'category',
      label: 'Python Utilities',
      items: [
        'python/clean-pdf',
        'python/daterange-checker',
        'python/collapse-checker',
        'python/htmlAttributesExtract',
        'python/latex2unicode',
      ],
    },
    {
      type: 'category',
      label: 'Shell Utilities',
      items: [
        'shell/embed',
        'shell/upload',
        'shell/download-title',
        'shell/gwsed',
      ],
    },
    {
      type: 'category',
      label: 'HTML Templates',
      items: [
        'templates/default',
        'templates/sourcecode',
        'templates/annotation-blockquote-not',
        'templates/annotation-partial-inline',
        'templates/github-issue-blockquote-not',
        'templates/github-issue-blockquote-outside',
        'templates/google-cse',
        'templates/google-search',
        'templates/tweet-blockquote-not',
        'templates/tweet-blockquote-outside',
        'templates/wikipedia-entry-blockquote-inside',
        'templates/wikipedia-entry-blockquote-not',
        'templates/wikipedia-entry-blockquote-title-not',
        'templates/include-footer',
        'templates/include-sidebar',
        'templates/include-inlined-asset-links',
        'templates/include-inlined-head',
        'templates/include-inlined-standalone',
        'templates/template-html5-articleedit',
        'templates/idealconditionsdonotexistandwillneverhappen',
        'templates/unfortunatelytheclockisticking',
      ],
    },
    {
      type: 'category',
      label: 'Server & Nginx',
      items: [
        'nginx/gwern-net-conf',
        'nginx/redirect-nginx',
        'nginx/redirect-nginx-broken',
        'nginx/memoriam-sh',
        'nginx/rsyncd-conf',
        'nginx/twdne-conf',
      ],
    },
  ],
};

export default sidebars;
